### ISSUE TITLE
waiting for ssh become available

### ISSUE THREAD

**Issue by sun9git** [rapid7/metasploitable3#70] opened 2016-12-16 04:19 UTC
## Issue Description
Please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System windows10
* OS:windows2008_r2
* Packer Version:0.12.0
* Vagrant Version:1.9.1
* VirtualBox Version:5.1.6

## Command Output
ps packer build .\windows_2008_r2.json

**Comment by sun9git** [comment] 2016-12-16 06:18
[1;32mvirtualbox-iso output will be in this color.[0m

[1;32m==> virtualbox-iso: Downloading or copying Guest additions[0m
[0;32m    virtualbox-iso: Downloading or copying: file:///D:/Program%20Files/Oracle/Virtua
0m
[1;32m==> virtualbox-iso: Downloading or copying ISO[0m
[0;32m    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7
D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso[0m
[1;32m==> virtualbox-iso: Creating floppy disk...[0m
[0;32m    virtualbox-iso: Copying files flatly from floppy_files[0m
[0;32m    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml[0m
[0;32m    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat[0m
[0;32m    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1[0m
[0;32m    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecures
[0;32m    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.
[0;32m    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/digicert.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/equifax.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer[0m
[0;32m    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer[0m
[0;32m    virtualbox-iso: Done copying files from floppy_files[0m
[0;32m    virtualbox-iso: Collecting paths from floppy_dirs[0m
[0;32m    virtualbox-iso: Resulting paths from floppy_dirs : [][0m
[0;32m    virtualbox-iso: Done copying paths from floppy_dirs[0m
[1;32m==> virtualbox-iso: Creating virtual machine...[0m
[1;32m==> virtualbox-iso: Creating hard drive...[0m
[1;32m==> virtualbox-iso: Attaching floppy disk...[0m
[1;32m==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, et
[1;32m==> virtualbox-iso: Executing custom VBoxManage commands...[0m
[0;32m    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1481868382 --memory 20
[0;32m    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1481868382 --cpus 2[0
[1;32m==> virtualbox-iso: Starting the virtual machine...[0m
[0;32m    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5917[0m
[1;32m==> virtualbox-iso: Waiting 2m0s for boot...[0m





[1;32m==> virtualbox-iso: Typing the boot command...[0m
[1;32m==> virtualbox-iso: Waiting for SSH to become available...[0m




















[1;31m==> virtualbox-iso: Timeout waiting for SSH.[0m
[1;32m==> virtualbox-iso: Unregistering and deleting virtual machine...[0m
[1;32m==> virtualbox-iso: Deleting output directory...[0m
[1;31mBuild 'virtualbox-iso' errored: Timeout waiting for SSH.[0m

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for SSH.

**Comment by derhornspieler** [comment] 2016-12-16 07:05
Same issue for me.

**Comment by catmin** [comment] 2016-12-16 09:50
same

**Comment by sun9git** [comment] 2016-12-16 10:08
i found some mattle what is virtualmachien miss net.however,i set virtualbox net mode is bridge host net,it still don't work

**Comment by jooeji** [comment] 2016-12-16 14:47
same,so mach time on it.sadly!!! >o<

**Comment by busterb** [comment] 2016-12-16 14:49
I'm guessing you guys are not native English speakers. Could you tell us which languages you are using in your operating system? It could simply be a localization problem.

**Comment by busterb** [comment] 2016-12-16 14:52
Also, we really recommend bringing this up on a standard Linux distribution, like Ubuntu, Debian or Redhat.

Some folks have gotten it to come up on Windows, and we've had no issue here running it on Windows 8.1 or Windows 10, English, with 8+GB of ram and a fast SSD, but we've had a lot more reports of success on Linux systems due to better performance. The biggest reason for the timeout is simply because the underlying machine is much slower than the scripts expect.

**Comment by sun9git** [comment] 2016-12-16 15:44
i am sorry.My host is windows10 Enterprise Edition, using Chinese language, 8G memory and SSD, my virtual machine is vbox5.1.8, the installation of the image file is Windows Server 2008 R2.

**Comment by busterb** [comment] 2016-12-16 15:47
I have a hunch we may be looking for the wrong strings when running on non-English versions. Will take a look, thanks!

**Comment by sun9git** [comment] 2016-12-16 15:57
Thanks you! I choose the image file is metasploitable3 inside the json given, I think there should be no language problems

**Comment by derhornspieler** [comment] 2016-12-16 23:19
Has this been resolved yet?  The SSH apparently never becomes available and times out?

**Comment by derhornspieler** [comment] 2016-12-17 17:40
UPDATE
Go into Windows Server VM

Go to C:\Program Files\OpenSSH\ and manually run ssh-agent.exe

script resumed afterwards.

**Comment by sun9git** [comment] 2016-12-18 16:44
![image](https://cloud.githubusercontent.com/assets/15946469/21294910/bfb4d3f4-c583-11e6-948d-6b96e4353ef5.png)


@busterb  Excuse me, this is my screenshot of the virtual machine to run there packer json file to stay at the point。I use the virtual machine network NAT conversion, I guess it is not because of my physical hosts and virtual machines can not lead to the communication of the ssh overtime

**Comment by sun9git** [comment] 2016-12-18 16:47
![image](https://cloud.githubusercontent.com/assets/15946469/21294946/92e3e832-c584-11e6-9dd3-21a00a05c7d7.png)

**Comment by bcook-r7** [comment] 2016-12-19 15:33
Hi guys, where are you getting C:\Program Files\OpenSSH\ from? I have not observed that being installed through anything that the metasploitable3 scripts do. Are you installing this? http://www.mls-software.com/opensshd.html

**Comment by derhornspieler** [comment] 2016-12-19 16:48
@bcook-r7 It was already apart of windows 2008 when I logged in via RDP and used CMD to locate it.  I'm assuming it is installed at some point during the setup before it was hanging at the SSH.

**Comment by busterb** [comment] 2016-12-19 16:59
Interesting. I've been trying to reproduce this locally. Current observation:

  - first try on a clean Windows 2016 host, worked without issues
  - deleted everything started over, saw a hang waiting for SSH. Typed a couple of characters into the command window, it proceeded.

Working theory is that there is a hidden command prompt waiting for input that we're not seeing.

**Comment by derhornspieler** [comment] 2016-12-19 17:19
Wait, you are not using Windows 2008 r2?


On Dec 19, 2016, at 11:59 AM, Brent Cook <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. I've been trying to reproduce this locally. Current observation:

  *   first try on a clean Windows 2016 host, worked without issues
  *   deleted everything started over, saw a hang waiting for SSH. Typed a couple of characters into the command window, it proceeded.

Working theory is that there is a hidden command prompt waiting for input that we're not seeing.

**Comment by derhornspieler** [comment] 2016-12-19 19:10
@sun9git go into /bin directory and run it from powershell

**Comment by busterb** [comment] 2016-12-19 22:01
@derhornspieler I was simply doing the provisioning on a Windows 2016 box. The target is still a Windows 2008 r2 VM.

**Comment by tjsimmons** [comment] 2016-12-23 03:39
I'm also building this on Windows 10, English locale. Same issue - can't get past "waiting for ssh".

**Comment by putsi** [comment] 2017-02-02 15:45
I also had the same problem and it was fixed by increasing "boot_wait" from "2m" to "10m".

**Comment by anhchuyen** [comment] 2017-03-30 07:19
Hello everyone here, 
I followed the instruction to install Metasploitable3 on my MAC. But I had some issues when install, it was different with the guide. This is what I have done on my machine:
1. I installed packer and vagrant already
2. From Terminal, I run $packer build windows_2008_r2.json
Here is result: 
----
==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
==> virtualbox-iso: Deleting previous output directory...
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/digicert.cer
    virtualbox-iso: Copying file: ./resources/certs/equifax.cer
    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer
    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2287)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1490854997 --memory 4096
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1490854997 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://127.0.0.1:5902
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
----
It just stands here forever. :(
3. But I open Virtualbox manager, and I can see a new VM that called "packer-virtualbox-iso-1490854997", I boot it and Windows server 2008 started. I can see "vagrant" account on system. But it looks like a fresh install of WS 2008, because I don't see IIS and other services..
Is there any wrong here?

Hope to hear from all of you, thanks....
![screen shot 2017-03-30 at 2 19 12 pm](https://cloud.githubusercontent.com/assets/5973048/24491984/e532f802-1553-11e7-82fe-a9f0d55e2615.png)

**Comment by Chan9390** [comment] 2017-05-16 10:34
Hey @anhchuyen while the script displays `Waiting for SSH to become available...`, it actually waits for the SSH port of the guest VM to become available. It generally takes around a few minutes (sometimes 10) until SSH becomes available. 
Sometimes you might end up in `SSH timeout`. If this situation continues, please do follow the steps:
1) Do the packer build, wait till `Waiting for SSH to become available...` is shown.
2) Manually use rdp / virtualbox to login to the box (user:vagrant/pass:vagrant)
3) Go to `C:\Program Files\OpenSSH\bin` and start `ssh-agent.exe` manually.

This will make the SSH port available, and the packer will continue its job.
Please look at issue #20 for more details.

**Comment by Chan9390** [comment] 2017-05-16 10:41
Hey @sun9git, Vagrant is known to have issues on systems with non-Latin characters (and also with spaces in absolute path name of folders). If you are using a English version of Windows, I would recommend to pull the latest code and then build metasploitable3, as it has some patches to errors recently found errors.

**Comment by waringd** [comment] 2017-05-29 17:37
I am having the same issue, stuck on waiting for SSH. I have tried the:

I have tried the ssh-agent.exe but that doesn't make a difference.

I am building the box with a fresh install of the latest Kali Linux. Any help would be very grateful

**Comment by Chan9390** [comment] 2017-05-30 01:11
Hey @waringd , I would like to know the following:
- What is the size of RAM on your computer ?
- How much free space do you have on harddisk ?
- How did you install VirtualBox ? Did you just do `sudo apt-get install VirtualBox` or you downloaded the `.run` file from the official website and executed it ?
- What are the versions of Vagrant, Packer and VirtualBox ?

**Comment by dmknght** [comment] 2017-06-01 09:28
SSH is available on metasploitable without running ssh-agent.exe.
I tried changing port (in port-forwarding option) from random port to 22 (by running packer as root) but it didn't make any difference.

**Comment by edmtorres02** [comment] 2017-06-28 16:18
I got the same error wherein "waiting for SSH" would always time out, I logged in to the guest VM and it seems like nothing was downloaded, there is no OpenSSH folder under C:\Program Files. I connect to the internet thru a proxy server/settings. I'm guessing that the VM is not able to connect to the internet, where can I modfiy settings to provide proxy credentials to the guest VM?

**Comment by Chan9390** [comment] 2017-06-29 00:28
@edmtorres02 Please delete the VM and try to rebuild it.

**Comment by dmknght** [comment] 2017-06-30 09:38
I confirmed that 'waiting for SSH' trying to download applications and install them. I just ran the packer and passed this error without any reason.

**Comment by Chan9390** [comment] 2017-06-30 09:49
@dmknght The build process is now changed. The download and installation is now moved to packer.

**Comment by dmknght** [comment] 2017-06-30 12:52
thanks for that information. But i did not update my source or did any thing lol. I just ran and somehow it worked. I got winrm error too but it fixed by `vagrant plugin install winrm winrm-fs`. I found out that if i install 1 plugin / 1 command, it did not work.
p/s: oops! Wrong topic!!

**Comment by scottgoetz** [comment] 2017-07-11 03:27
I had this issue with VMware. I realized that the Virtual Network I was using for NAT was not setup to handle traffic local/host traffic, it only allowed connections to the internet. 

To fix this problem go to Edit > Virtual Network Editor > Select NAT network > check "Connect a host virtual adapter to this network". You can do this right away during the Windows setup..

**Closed** 2017-08-10 17:12 UTC

**Comment by Kinfedge** [comment] 2017-11-15 14:00
I got the same error “Waiting for SSH”，but I just change the version of vagrant and virtualbox passed the error. Hope this can help anybody have the same problem.

**Comment by Kinfedge** [comment] 2017-11-15 14:02
vagrant 1.9.6 virtualbox 5.1.28 windows10 x64

**Comment by Chan9390** [comment] 2017-11-15 15:42
Metasploitable 3 was not tested against vagrant 1.9.6, please install the recommended version.

**Comment by memorycancel** [comment] 2024-10-26 14:49
> I got the same error wherein "waiting for SSH" would always time out, I logged in to the guest VM and it seems like nothing was downloaded, there is no OpenSSH folder under C:\Program Files. I connect to the internet thru a proxy server/settings. I'm guessing that the VM is not able to connect to the internet, where can I modfiy settings to provide proxy credentials to the guest VM?

Hi @edmtorres02 , same issue to me, did you solve the proxy?
