### ISSUE TITLE
failing at rubygems?  virtualbox-iso: Script exited with non-zero exit status: 1

### ISSUE THREAD

**Issue by e28shrkattk** [rapid7/metasploitable3#179] opened 2017-08-18 01:32 UTC
## Description 
when running the ps1 script I was receiving  a similar error this was generated by running "packer build .\windows_2008_r2.json"

I now think its failing in install_rails_server.bat 

I have removed my antivirus because that was causing earlier issues with some scripts, that is about all I have tried, im not even sure what its failing on, any help would be appreciated, thank you in advance. 

## Host System
* OS: windows 7 pro
* Packer Version:  v1.0.4 ,tried  1.0.1 same result
* Vagrant Version: 1.9.7  , tried downgrading to 1.9.1, same result 
* VirtualBox Version:  5.1.26 , tried 5.1.10 same result

## output:
"    virtualbox-iso: C:\Users\vagrant>copy /Y C:\Vagrant\Resources\rails_server\sqlite3-1.3.11-x64-mingw32.gemspec C:\too
ls\ruby23\lib\ruby\gems\2.3.0\specifications
    virtualbox-iso: 1 file(s) copied.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"
    virtualbox-iso: exist
    virtualbox-iso: C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb:140:in `cre
ate_root': uninitialized constant Rails::Generators::AppBase::FileUtils (NameError)
    virtualbox-iso: Did you mean?  FileTest
    virtualbox-iso: from (eval):1:in `create_root'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_comm
and'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in in
voke_all'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'

    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/commands/application.rb:17:in
 `<top (required)>'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/cli.rb:14:in `<top (required)
>'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    virtualbox-iso: from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/bin/rails:9:in `<top (required)>'
    virtualbox-iso: from C:/tools/ruby23/bin/rails:22:in `load'
    virtualbox-iso: from C:/tools/ruby23/bin/rails:22:in `<main>'
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* VMware application not found:
* VMware application not found:

--> virtualbox-iso: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.  "

**Comment by Chan9390** [comment] 2017-08-18 13:38
Did you try downgrading your VirtualBox ?

**Comment by e28shrkattk** [comment] 2017-08-18 15:52
installing virtualbox 5.1.6 now 
fingers crossed

**Comment by e28shrkattk** [comment] 2017-08-18 17:14
same result with 5.1.10

**Comment by Chan9390** [comment] 2017-08-19 08:43
This is a ruby gem issue. I have the same problem on my side.

**Comment by jbarnett-r7** [comment] 2017-08-21 16:47
This is a duplicate of #180. Keeping that one because it has a little more information.

**Closed by jbarnett-r7** 2017-08-21 16:47 UTC
