### ISSUE TITLE
Vmware workstation network issue

### ISSUE THREAD

**Issue by bhaizlett123** [rapid7/metasploitable3#188] opened 2017-09-26 12:36 UTC
## Issue Description
I have successfully been able to run it in virtual box with everything working. Now i have exported the appliance and i load it into vmware workstation, everything seems to be up, except i can't get a network connection, i can't even get into the networks connections menu, has anyone else experienced something similar with vmware workstation and metasploitable3?

## Host System
*OS: Windows 10 pro x64
*Packer Version: 1.1.0
*Vagrant Version: 1.9.1
*VirtualBox Version: 5.1.28

**Comment by jmartin-r7** [comment] 2017-11-22 17:15
Unfortunately migration of VM platforms can result in new network hardware identification by the OS. This can conflict with the pre-built service configurations.  You would need to manually reconfigure the VM to get services running on the new network interfaces when this occurs.

Optionally, you can build directly agains VMware Workstation using `packer build --only-vmware-iso windows_2008_r2.json`.  This should result in a *.box* file you can simply unzip and load in VMware without vagrant.

Closing as this as not an issue caused by *metasploitable3* it is an artifact for virtualization env compatibility.

**Closed by jmartin-r7** 2017-11-22 17:15 UTC
