### ISSUE TITLE
Missing WAMP Apache Service (Port 8585)

### ISSUE THREAD

**Issue by TobinShields** [rapid7/metasploitable3#315] opened 2018-07-16 19:08 UTC
## Issue Description
I have just built my Metasploitable3 box and I am happy that I got it to work after lots of troubleshooting. I am moving through [Jeremy Druin's referenced YouTube playlist](https://www.youtube.com/playlist?list=PLZOToVAK85MpnjpcVtNMwmCxMZRFaY6mT), and I am noticing a discrepancy between the services that he has running on his VM and what I am seeing in my own. In the screenshots below, you can see his nmap output and my nmap output. I am using Kali Linux 2018.2 to scan Metasploitable 3. 

Specifically, I am wondering why I do not see the WAMP Apache (port 8585) service? I have verified that WAMP is running on Metasploitable3 and that I can actually connect via Kali if I manually type in the IP address :8585. But how would I have discovered that in the first place if the nmap scan didn't show it? 

## Host System
* OS: Windows 10
* Packer Version: 1.2.4
* Vagrant Version: 2.1.2
* VirtualBox Version: 5.2.8

## Command Output
**Jeremy Druin's Tutorial nmap output**
![image](https://user-images.githubusercontent.com/20485100/42777500-20e19f56-88ef-11e8-97df-849f8fec7d9f.png)
**My nmap output**
![image](https://user-images.githubusercontent.com/20485100/42777523-3520af2a-88ef-11e8-97e5-e4914156cd96.png)

**Comment by rtmoran0** [comment] 2018-07-24 21:55
Running the same setup as you with a recent metaploitable3 build and have run into the same issue. My open ports match yours exactly. Let me know if you've found a solution.

**Comment by TobinShields** [comment] 2018-07-25 17:05
I still do not have a solution to this problem. I think that [another user](https://github.com/rapid7/metasploitable3/issues/314) is reporting having some missing services as well. I am sorry to say that I don't know enough about how packer and vagrant work to begin to troublehsoot these problems.

**Comment by jmartin-r7** [comment] 2018-08-05 21:48
This is likely a networking issue either in resources or configuration on your environment.  This kind of thing is part of the reason for using something like metasploitable3.  From interaction you learn that not all networks are created equal. In this case likely packets are lost to or from kali and the metasploitable3 windows VM.  Are there other VMs running? Is there a possible IP conflict?  All this and more can create behavior like you see.

Since others confirm similar behaviour and service is up in the metasploitable3 VM and reachable directly, I am closing this as not a bug in metasploitable3-win2k8.

**Closed by jmartin-r7** 2018-08-05 21:48 UTC
