### ISSUE TITLE
Packet does not build ".box" file

### ISSUE THREAD

**Issue by ManuelBerrueta** [rapid7/metasploitable3#304] opened 2018-06-26 15:17 UTC
## Issue Description
**Packer does not make the `.box` file.**

After a few attempts at attempting to build Metasploitable3 with the script ending with errors I decided to do a manual install to build it manually and it still ends up with same error. As a result I am not able to add the `windows_2008_r2_virtualbox.box` because there is no such thing, and therefore I can not get vagrant up/

As of right now I have a bootable Virtualbox image but I am sure it doesn't have all the goodies it should have. 

I have tried uninstalling and deleting everything and I still end up with the same result.

## Host System
* OS: Windows 10 Enterprise, Version 1709, Build 16299.431
* Packer Version: 1.2.4_amd64
* Vagrant Version: 2.1.1
* VirtualBox Version: 5.2.12 r122591

## Command Output
```
    virtualbox-iso: C:\Users\vagrant>powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip', 'C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip')"  0<NUL
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred
    virtualbox-iso: during a WebClient request."
    virtualbox-iso: At line:1 char:96
    virtualbox-iso: + ... pe]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://g ...
    virtualbox-iso: +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : WebException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"
    virtualbox-iso:
    virtualbox-iso: ERROR: The system cannot find the file specified.
    virtualbox-iso: C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: 7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: Scanning the drive for archives:
    virtualbox-iso: System ERROR:
    virtualbox-iso: The system cannot find the file specified.

==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Error deleting VM: VBoxManage error: VBoxManage.exe: error: Could not find a registered machine named 'metasploitable3-win2k8'
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "FindMachine(Bstr(VMName).raw(), machine.asOutParam())" at line 153 of file VBoxManageMisc.cpp
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Failed creating VMware driver: Unable to initialize any driver for this platform. The errors
from each driver are shown below. Please fix at least one driver
to continue:
* VMware application not found:
* VMware application not found:
* 'vmrun' application not found:
* 'vmrun' application not found:

--> virtualbox-iso: Script exited with non-zero exit status: 2

==> Builds finished but no artifacts were created.
```

**Comment by KairatKempirbaev** [comment] 2018-07-01 09:36
C:\Users\YOUR_NAME\Documents\metasploitable3\packer\builds

**Comment by KairatKempirbaev** [comment] 2018-07-01 09:36
Check it in that folder

**Comment by KairatKempirbaev** [comment] 2018-07-01 09:37
If step 2 is done it should be over there.

**Comment by KairatKempirbaev** [comment] 2018-07-01 09:42
edit vagrant file to 
`  config.vm.define "win2k8" do |win2k8|
    # Base configuration for the VM and provisioner
    win2k8.vm.box = "metasploitable3"
    win2k8.vm.hostname = "metasploitable3"
`

**Comment by KairatKempirbaev** [comment] 2018-07-01 10:07
After all that i could say i learned vagrant:)

**Comment by KairatKempirbaev** [comment] 2018-07-01 10:11
You could have problems with no network.
init box after that provision.
I guess....

**Comment by KairatKempirbaev** [comment] 2018-07-01 10:39
I give up. Would build under linux.

**Comment by gametimebrizzle** [comment] 2018-07-07 00:05
I'm in same boat, see my issue #309

**Comment by gametimebrizzle** [comment] 2018-07-07 00:09
C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x "C:\Windows\Temp\openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6"

openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -oC:\openjdk6

should be:
openjdk-1.6.0-unofficial-b27-windows-amd64.zip" -o C:\openjdk6

That's why it can't find it

**Comment by gametimebrizzle** [comment] 2018-07-07 00:11
Vbox file is in the hidden '.vagrant.d' folder in %USER_HOME%

**Comment by TheLinuxNinja** [comment] 2018-07-11 05:59
Looks like your script failed when your client tried to download:
`https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip`

I've confirmed that file is downloadable.

Did you try to `vagrant destroy` and start over?

**Comment by ManuelBerrueta** [comment] 2018-07-25 04:57
Hello,

Yea I destroyed it and tried a variety of different things. It seems like I tried everything under the sun. I put that project on hold for now. 

Thanks for trying though!

**Comment by jmartin-r7** [comment] 2018-07-26 02:49
Based on the log in your report, your powershell running in the vm could not reach `https://github.com/downloads/alexkasko/openjdk-unofficial-builds/openjdk-1.6.0-unofficial-b27-windows-amd64.zip` to download and install it.  This is was a connectivity issue during the build.

Closing as not a bug.

**Closed by jmartin-r7** 2018-07-26 02:49 UTC
