### ISSUE TITLE
vagrant up - Error Message

### ISSUE THREAD

**Issue by heckflosse1976** [rapid7/metasploitable3#311] opened 2018-07-09 11:10 UTC
Hi,
i have installed metsploitable3 on a Linux Mint with VirtualBox. Installation works fine. When i start with "vagrant up" i get this error message:
```
mm@ThinkPad:~/Downloads/metasploitable3$ vagrant up
Traceback (most recent call last):
	23: from /usr/bin/vagrant:23:in `<main>'
	22: from /usr/bin/vagrant:23:in `load'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/bin/vagrant:146:in `<top (required)>'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:269:in `cli'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/cli.rb:46:in `execute'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/commands/up/command.rb:87:in `execute'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `each'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:694:in `machine'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `machine'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `new'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:140:in `initialize'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:248:in `communicate'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/registry.rb:27:in `get'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:12:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- winrm-elevated (LoadError)
```
Many thanks for all your answers.
Markus

**Comment by TheLinuxNinja** [comment] 2018-07-11 05:48
vagrant plugin install winrm winrm-fs

Did you read through https://github.com/rapid7/metasploitable3/wiki/General-Issues ?

**Comment by jmartin-r7** [comment] 2018-08-08 07:46
What OS is this on? Vagrant packages being distributed with some distros have knows issues with either not including or having inconsistent vagrant `winrm` support.

If you installed via the default package manager, I suggest to try uninstalling vagrant and installing using a package downloaded directly from https://www.vagrantup.com/downloads.html

**Comment by jmartin-r7** [comment] 2018-08-29 17:18
Closing, this is an issue in the `vagrant` env not a bug in the metasploitable3 build.

**Closed by jmartin-r7** 2018-08-29 17:18 UTC
