### ISSUE TITLE
Issue building on MacOS for VMWare Fusion

### ISSUE THREAD

**Issue by jjohnson-anomalix** [rapid7/metasploitable3#342] opened 2018-09-22 01:11 UTC
## Issue Description
Having a lot of problems building metasploitable3 using the latest versions of Packer (1.3.1) and Vagrant (2.1.5) for VMWare.  Executing command:  ./build.sh ubuntu1404; I had to make adjustments to get it to work at at all:

Line 70:  providers="vmware"
Line 121: if compare_versions $(vagrant plugin list | grep 'vagrant-reload' | cut -d' ' -f2 | tr -d '(' | tr -d ')' | tr -d ',') $min_vagrantreload_ver false; then

With the following adjustments I can see the VM start up and it works long enough for it to install/configure all of the services, but something goes wrong at the end of the script, and the VM becomes corrupt and displays "File not found" in VMWare Fusion.  The box file is created, however the vmx, vmdk, etc. files for VMWare are gone from the file system.  I tried clearing packer and vagrant and starting over with older versions listed on the "General Issues" page:  Packer 1.2.3, Vagrant 1.9.1.  But I cannot proceed as my vmware plugin license apparently is incompatible with the older version:

```
$ vagrant init hashicorp/precise64
The Vagrant VMware provider requires a valid license
to run. The license provided is invalid. Please make sure you
downloaded the proper license. If you believe you're seeing
this message in error, please contact support.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
$ vagrant --version
Vagrant 1.9.1
```

## Host System
* OS: macOS High Sierra v10.13.6
* Packer Version: 1.3.1
* Vagrant Version: 2.1.5
* VMware Version: VMware Fusion Pro 10.1.3

## Command Output
```
==> vmware-iso: Skipping export of virtual machine (export is allowed only for ESXi)...
==> vmware-iso: Running post-processor: vagrant
==> vmware-iso (vagrant): Creating Vagrant box for 'vmware' provider
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s001.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s002.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s003.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s004.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s005.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s006.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s007.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s008.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s009.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk-s010.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/disk.vmdk
    vmware-iso (vagrant): Copying: output-vmware-iso/metasploitable3-ub1404.nvram
    vmware-iso (vagrant): Copying: output-vmware-iso/metasploitable3-ub1404.vmsd
    vmware-iso (vagrant): Copying: output-vmware-iso/metasploitable3-ub1404.vmx
    vmware-iso (vagrant): Copying: output-vmware-iso/metasploitable3-ub1404.vmxf
    vmware-iso (vagrant): Compressing: Vagrantfile
    vmware-iso (vagrant): Compressing: disk-s001.vmdk
    vmware-iso (vagrant): Compressing: disk-s002.vmdk
    vmware-iso (vagrant): Compressing: disk-s003.vmdk
    vmware-iso (vagrant): Compressing: disk-s004.vmdk
    vmware-iso (vagrant): Compressing: disk-s005.vmdk
    vmware-iso (vagrant): Compressing: disk-s006.vmdk
    vmware-iso (vagrant): Compressing: disk-s007.vmdk
    vmware-iso (vagrant): Compressing: disk-s008.vmdk
    vmware-iso (vagrant): Compressing: disk-s009.vmdk
    vmware-iso (vagrant): Compressing: disk-s010.vmdk
    vmware-iso (vagrant): Compressing: disk.vmdk
    vmware-iso (vagrant): Compressing: metadata.json
    vmware-iso (vagrant): Compressing: metasploitable3-ub1404.nvram
    vmware-iso (vagrant): Compressing: metasploitable3-ub1404.vmsd
    vmware-iso (vagrant): Compressing: metasploitable3-ub1404.vmx
    vmware-iso (vagrant): Compressing: metasploitable3-ub1404.vmxf
Build 'vmware-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> vmware-iso: 'vmware' provider box: /Users/jjohnson/Documents/dev/metasploitable3-workspace/metasploitable3/packer/templates/../builds/ubuntu_1404_vmware_0.1.12.box
Boxes successfully built by Packer.
Attempting to add the box to Vagrant...
rapid7/metasploitable3-ub1404 already found in Vagrant box repository. Skipping the addition to Vagrant.
NOTE: If you are having issues, try starting over by doing 'vagrant destroy' and then 'vagrant up'.
---------------------------------------------------------------------
SUCCESS: Run 'vagrant up' to provision and start metasploitable3.
NOTE: The VM will need Internet access to provision properly.
```

**Comment by jjohnson-anomalix** [comment] 2018-09-22 01:14
Some output to show the status of the vagrant environment:

$ vagrant box list
hashicorp/precise64           (vmware_fusion, 1.1.0)
rapid7/metasploitable3-ub1404 (vmware_desktop, 0)

$ vagrant status
Current machine states:

default                   not running (vmware_desktop)

The VM is powered off. To restart the VM, run `vagrant up`

**Comment by jmartin-r7** [comment] 2018-12-11 05:12
Sorry for the delayed response, I have opened a PR for the adjustment to get the vmware plugin detected by `build.sh`.

Due to the way packer builds the vagrant box the VMware Fusion Library will contain a leftover entry after build that is not connected to vagrant.  This should just be deleted from the inventory.

As to your issue I cannot reproduce it, the VM built successfully however I did have to specify the `vmware_fusion` provider to get it to launch as `vagrant up --provider vmware_fusion ub1404`.

Once launched I am able to interact with the VM.

```
metasploitable3 jmartin$ vagrant box list
rapid7/metasploitable3-ub1404 (vmware_desktop, 0)

metasploitable3 jmartin$ vagrant up --provider vmware_fusion ub1404
Bringing machine 'ub1404' up with 'vmware_fusion' provider...
==> ub1404: Cloning VMware VM: 'rapid7/metasploitable3-ub1404'. This can take some time...
==> ub1404: Verifying vmnet devices are healthy...
==> ub1404: Preparing network adapters...
WARNING: The VMX file for this box contains a setting that is automatically overwritten by Vagrant
WARNING: when started. Vagrant will stop overwriting this setting in an upcoming release which may
WARNING: prevent proper networking setup. Below is the detected VMX setting:
WARNING:
WARNING:   ethernet0.pcislotnumber = "33"
WARNING:
WARNING: If networking fails to properly configure, it may require this VMX setting. It can be manually
WARNING: applied via the Vagrantfile:
WARNING:
WARNING:   Vagrant.configure(2) do |config|
WARNING:     config.vm.provider :vmare_fusion do |vmware|
WARNING:       vmware.vmx["ethernet0.pcislotnumber"] = "33"
WARNING:     end
WARNING:   end
WARNING:
WARNING: For more information: https://www.vagrantup.com/docs/vmware/boxes.html#vmx-whitelisting
==> ub1404: Fixed port collision for 22 => 2222. Now on port 2200.
==> ub1404: Starting the VMware VM...
==> ub1404: Waiting for the VM to receive an address...
==> ub1404: Forwarding ports...
    ub1404: -- 22 => 2200
==> ub1404: Waiting for machine to boot. This may take a few minutes...
    ub1404: SSH address: 127.0.0.1:2200
    ub1404: SSH username: vagrant
    ub1404: SSH auth method: password
    ub1404:
    ub1404: Inserting generated public key within guest...
    ub1404: Removing insecure key from the guest if it's present...
    ub1404: Key inserted! Disconnecting and reconnecting using new SSH key...
==> ub1404: Machine booted and ready!
==> ub1404: Setting hostname...
==> ub1404: Configuring network adapters within the VM...
metasploitable3 jmartin$ vagrant ssh ub1404
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
vagrant@metasploitable3-ub1404:~$
```

**Comment by usmcfiredog** [comment] 2018-12-23 15:39
One issue I know with this is that provider Vmware_fusion has been depreciated and it now uses vmware_desktop for all versions of VMware.

**Comment by jmartin-r7** [comment] 2018-12-23 18:55
You can still specify `--provider vmware_fusion` with plugin `vagrant-vmware-fusion (5.0.4)`  this will pull and interact with vmware_desktop vagrant boxes from vagrant cloud.

**Comment by usmcfiredog** [comment] 2018-12-23 18:57
It used to error out for me and I had to manually put --provider Vmware_desktop in order to get it to work. Thats why I was making the comment.

**Comment by jmartin-r7** [comment] 2018-12-26 01:19
Closing issue as unable to reproduce.

**Closed by jmartin-r7** 2018-12-26 01:19 UTC
