### ISSUE TITLE
The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 3389 (Errno::EADDRNOTAVAIL)

### ISSUE THREAD

**Issue by oneshoturdone** [rapid7/metasploitable3#134] opened 2017-04-17 21:39 UTC
## Issue Description
I've tried building this thing nested, inside a Kali VM, which failed as well, so I tried building it in Windows and received a different error. At first I thought this error was perhaps related to the fact that I had RDP services running on my local box but disabling that didn't fix the issue either. In other threads I saw mentions of disabling Windows firewall. I have not tried downgrading my Virtualbox version. I've built about 7 other Vagrant environments with the 'pentest-env' project. Their version of metasploitable is a prebuilt image with an expired license, and I would honestly prefer to just build it myself.

My build is failing at the 'vagrant up' portion of the instructions. Prior steps complete successfully with no apparent errors or issues.

## Host System
* OS: Windows 10
* Packer Version:1.0.0
* Vagrant Version:1.9.3
* VirtualBox Version:5.1.18

## Command Output
PS C:\tools\metasploitable3-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'metasploitable3'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: metasploitable3-master_default_1492456002954_64933
==> default: Cookbook fetching disabled, skipping
==> default: Running cleanup tasks for 'reload' provisioner...
==> default: Running cleanup tasks for 'reload' provisioner...
==> default: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/is_port_open.rb:21:in `initialize': The requested address is not valid in its context. - connect(2) for "0.0.0.0" port 3389 (Errno::EADDRNOTAVAIL)

**Full output here:
https://pastebin.com/XNkAS272

**Comment by jbarnett-r7** [comment] 2017-04-17 21:42
Thanks for the detailed report! It looks like this is a duplicate of #106 which is a bug in Vagrant 1.9.3. They already have a fix, but haven't put a release out yet. In the meantime you can downgrade Vagrant to 1.9.2 to work around this.

**Comment by oneshoturdone** [comment] 2017-04-17 21:43
Thanks for the super fast reply, I'll give it a go right now.

**Closed by jbarnett-r7** 2017-04-17 21:42 UTC
