### ISSUE TITLE
Waiting for SSH...

### ISSUE THREAD

**Issue by lgcambero** [rapid7/metasploitable3#50] opened 2016-11-18 20:23 UTC
Any ideas??
![1](https://cloud.githubusercontent.com/assets/11602705/20445401/b07a2318-adb3-11e6-8f9e-49c4b8c92143.jpg)

**Comment by jbarnett-r7** [comment] 2016-11-21 15:58
This is a dupe of #20 Closing it to keep things consolidated.

**Closed by jbarnett-r7** 2016-11-21 15:58 UTC
Labels: duplicate
