### ISSUE TITLE
Tomcat Server Failure with provisioning 'C:\ProgramData\chocolatey\lib\Tomcat\tools\chocolateyInstall.ps1'.

### ISSUE THREAD

**Issue by derhornspieler** [rapid7/metasploitable3#74] opened 2016-12-19 18:00 UTC
==> default: Download of apache-tomcat-8.0.33-windows-x64.zip (10.37 MB) completed.
==> default: Hashes match.
==> default: Extracting C:\Users\vagrant\AppData\Local\Temp\chocolatey\Tomcat\8.0.33\apache-tomcat-8.0.33-windows-x64.zip to C:\Program Files\Apache Software Foundation\tomcat...
==> default: C:\Program Files\Apache Software Foundation\tomcat
==> default: #< CLIXML
==> default: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="debug">Host version is 2.0, PowerShell Version is '2.0' and CLR Version is '2.0.50727.5420'.</S><S S="verbose">Exporting function 'Format-FileSize'.</S><S S="verbose">Exporting function 'Get-ChecksumValid'.</S><S S="verbose">Exporting function 'Get-ChocolateyUnzip'.</S><S S="verbose">Exporting function 'Get-ChocolateyWebFile'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Get-EnvironmentVariableNames'.</S><S S="verbose">Exporting function 'Get-FtpFile'.</S><S S="verbose">Exporting function 'Get-OSArchitectureWidth'.</S><S S="verbose">Exporting function 'Get-ToolsLocation'.</S><S S="verbose">Exporting function 'Get-UACEnabled'.</S><S S="verbose">Exporting function 'Get-UninstallRegistryKey'.</S><S S="verbose">Exporting function 'Get-VirusCheckValid'.</S><S S="verbose">Exporting function 'Get-WebFile'.</S><S S="verbose">Exporting function 'Get-WebFileName'.</S><S S="verbose">Exporting function 'Get-WebHeaders'.</S><S S="verbose">Exporting function 'Install-BinFile'.</S><S S="verbose">Exporting function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Exporting function 'Install-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Install-ChocolateyExplorerMenuItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyFileAssociation'.</S><S S="verbose">Exporting function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyPath'.</S><S S="verbose">Exporting function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Exporting function 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Exporting function 'Install-ChocolateyShortcut'.</S><S S="verbose">Exporting function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">Exporting function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Install-Vsix'.</S><S S="verbose">Exporting function 'Set-EnvironmentVariable'.</S><S S="verbose">Exporting function 'Set-PowerShellExitCode'.</S><S S="verbose">Exporting function 'Start-ChocolateyProcessAsAdmin'.</S><S S="verbose">Exporting function 'Test-ProcessAdminRights'.</S><S S="verbose">Exporting function 'Uninstall-BinFile'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Exporting function 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Exporting function 'Update-SessionEnvironment'.</S><S S="verbose">Exporting function 'Write-ChocolateyFailure'.</S><S S="verbose">Exporting function 'Write-ChocolateySuccess'.</S><S S="verbose">Exporting function 'Write-FileUpdateLog'.</S><S S="verbose">Exporting function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Exporting alias 'Get-ProcessorBits'.</S><S S="verbose">Exporting alias 'Get-OSBitness'.</S><S S="verbose">Exporting alias 'Get-InstallRegistryKey'.</S><S S="verbose">Exporting alias 'Generate-BinFile'.</S><S S="verbose">Exporting alias 'Add-BinFile'.</S><S S="verbose">Exporting alias 'Start-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Exporting alias 'Remove-BinFile'.</S><S S="verbose">Exporting alias 'refreshenv'.</S><S S="verbose">Importing function 'Format-FileSize'.</S><S S="verbose">Importing function 'Get-ChecksumValid'.</S><S S="verbose">Importing function 'Get-ChocolateyUnzip'.</S><S S="verbose">Importing function 'Get-ChocolateyWebFile'.</S><S S="verbose">Importing function 'Get-EnvironmentVariable'.</S><S S="verbose">Importing function 'Get-EnvironmentVariableNames'.</S><S S="verbose">Importing function 'Get-FtpFile'.</S><S S="verbose">Importing function 'Get-OSArchitectureWidth'.</S><S S="verbose">Importing function 'Get-ToolsLocation'.</S><S S="verbose">Importing function 'Get-UACEnabled'.</S><S S="verbose">Importing function 'Get-UninstallRegistryKey'.</S><S S="verbose">Importing function 'Get-VirusC
==> default: heckValid'.</S><S S="verbose">Importing function 'Get-WebFile'.</S><S S="verbose">Importing function 'Get-WebFileName'.</S><S S="verbose">Importing function 'Get-WebHeaders'.</S><S S="verbose">Importing function 'Install-BinFile'.</S><S S="verbose">Importing function 'Install-ChocolateyDesktopLink'.</S><S S="verbose">Importing function 'Install-ChocolateyEnvironmentVariable'.</S><S S="verbose">Importing function 'Install-ChocolateyExplorerMenuItem'.</S><S S="verbose">Importing function 'Install-ChocolateyFileAssociation'.</S><S S="verbose">Importing function 'Install-ChocolateyInstallPackage'.</S><S S="verbose">Importing function 'Install-ChocolateyPackage'.</S><S S="verbose">Importing function 'Install-ChocolateyPath'.</S><S S="verbose">Importing function 'Install-ChocolateyPinnedTaskBarItem'.</S><S S="verbose">Importing function 'Install-ChocolateyPowershellCommand'.</S><S S="verbose">Importing function 'Install-ChocolateyShortcut'.</S><S S="verbose">Importing function 'Install-ChocolateyVsixPackage'.</S><S S="verbose">Importing function 'Install-ChocolateyZipPackage'.</S><S S="verbose">Importing function 'Install-Vsix'.</S><S S="verbose">Importing function 'Set-EnvironmentVariable'.</S><S S="verbose">Importing function 'Set-PowerShellExitCode'.</S><S S="verbose">Importing function 'Start-ChocolateyProcessAsAdmin'.</S><S S="verbose">Importing function 'Test-ProcessAdminRights'.</S><S S="verbose">Importing function 'Uninstall-BinFile'.</S><S S="verbose">Importing function 'Uninstall-ChocolateyEnvironmentVariable'.</S><S S="verbose">Importing function 'Uninstall-ChocolateyPackage'.</S><S S="verbose">Importing function 'Uninstall-ChocolateyZipPackage'.</S><S S="verbose">Importing function 'Update-SessionEnvironment'.</S><S S="verbose">Importing function 'Write-ChocolateyFailure'.</S><S S="verbose">Importing function 'Write-ChocolateySuccess'.</S><S S="verbose">Importing function 'Write-FileUpdateLog'.</S><S S="verbose">Importing function 'Write-FunctionCallLogMessage'.</S><S S="verbose">Importing alias 'Add-BinFile'.</S><S S="verbose">Importing alias 'Generate-BinFile'.</S><S S="verbose">Importing alias 'Get-InstallRegistryKey'.</S><S S="verbose">Importing alias 'Get-OSBitness'.</S><S S="verbose">Importing alias 'Get-ProcessorBits'.</S><S S="verbose">Importing alias 'Invoke-ChocolateyProcess'.</S><S S="verbose">Importing alias 'refreshenv'.</S><S S="verbose">Importing alias 'Remove-BinFile'.</S><S S="verbose">Importing alias 'Start-ChocolateyProcess'.</S></Objs>
==> default: 0
==> default: ERROR: Cannot bind parameter 'FilterScript'. Cannot convert the "Name" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
==> default: Environment Vars (like PATH) have changed. Close/reopen your shell to
==> default:  see the changes (or in powershell/cmd.exe just type `refreshenv`).
==> default: The install of tomcat was NOT successful.
==> default: Error while running 'C:\ProgramData\chocolatey\lib\Tomcat\tools\chocolateyInstall.ps1'.
==> default: 
==> default:  See log for details.
==> default: Chocolatey installed 1/2 packages. 1 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: Failures
==> default:  - tomcat (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\Tomcat\tools\chocolateyInstall.ps1'.
==> default:  See log for details.

**Comment by derhornspieler** [comment] 2016-12-23 05:27
@jbarnett-r7 I have run this manually in powershell and produce the exact same error.  Is this a chocolatey error that needs addressed?

**Comment by jbarnett-r7** [comment] 2017-01-11 21:13
@derhornspieler It's possible that chocolatey had a bug in their install script when you were attempting to run this. That error looks like it's happening in their code. Are you still seeing the problem?

**Comment by MichaelKofler** [comment] 2017-01-22 06:51
same for me, error happens on first `vagrant up` command

**Comment by belkacimo** [comment] 2017-03-03 06:47
hello
i had similar issue and found out the virtual box tools were not installed because there was no cd drive on the VM. without tools, we can`t mount the share folder. virtual box version is 5.1.4

**Comment by scaredbitless** [comment] 2017-03-17 13:54
looks like this is still an issue. I had the same thing on first running `vagrant up`

**Comment by e4ch** [comment] 2017-03-21 12:29
I can confirm this issue is still happening with latest VirtualBox 5.1.18, Vagrant 1.9.2 and latest master of metasploitable3 (8b1af13) running on Windows 10 host. VirtualBox extensions are installed. Tomcat does start up later though, so I'm not sure what is missing - the script continues and this is only noticed when closely watching the log output.

**Comment by Chan9390** [comment] 2017-05-20 07:28
This issue has nothing to do with VirtualBox, Packer or Vagrant. It is an issue with `chocolatey` itself. The bug is not yet removed from the latest chocolatey build. 

Checkout the same discussion on tomcat in [chocolatey Google Group](https://groups.google.com/forum/#!searchin/chocolatey/tomcat|sort:relevance/chocolatey/QSs2EEcKRRg/9p3dKEZcBQAJ)

**Comment by Chan9390** [comment] 2017-05-20 10:13
There is no effect by the error and the build is not broken. **`tomcat` is installed** before the error message shows up.

**Comment by Chan9390** [comment] 2017-06-09 04:39
Closing issue as the error log doesnt affect the installation. If you get it again, please reopen.

**Closed by Chan9390** 2017-06-09 04:39 UTC
