### ISSUE TITLE
Vagrant up Failed

### ISSUE THREAD

**Issue by duncan426** [rapid7/metasploitable3#260] opened 2018-04-04 15:22 UTC
box successfully added to vagrant, but when I run Vagrant up I get this:  Newbie here.

* OS: Windows 10 Pro
* Packer Version: 1.2.2
* Vagrant Version: 2.03
* VirtualBox Version: 5.2.8

## Command Output
PS C:\Users\dunca\Documents\metasploitable3-master> vagrant up
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Box 'metasploitable3-win2k8-disk001' could not be found. Attempting to find and install...
    win2k8: Box Provider: virtualbox
    win2k8: Box Version: >= 0
==> win2k8: Box file was not detected as metadata. Adding it directly...
==> win2k8: Adding box 'metasploitable3-win2k8-disk001' (v0) for provider: virtualbox
    win2k8: Downloading: metasploitable3-win2k8-disk001
    win2k8:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/dunca/Documents/metasploitable3-master/metasploitable3-win2k8-disk001

**Comment by duncan426** [comment] 2018-04-04 15:50
i figured the first part out.  I removed -disk001.  Now I get:
 

win2k8: CMDKEY: Credential added successfully.
    win2k8: System error 67 has occurred.
    win2k8: The network name cannot be found.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cmd /q /c "c:\tmp\vagrant-shell.bat"

Stdout from the command:


CMDKEY: Credential added successfully.


Stderr from the command:

System error 67 has occurred.

The network name cannot be found.

**Comment by qingsword** [comment] 2018-04-05 11:08
OS：ubuntu16.04

$ ./build.sh windows2008
building windows 2008
Compatible version of VirtualBox found.
Compatible version of packer was found.
Correct version of vagrant was found.
Compatible version of vagrant-reload plugin was found.
All requirements found. Proceeding...
It looks like the vagrant box already exists. Skipping the Packer build.
Attempting to add the box to Vagrant...
metasploitable3-win2k8 already found in Vagrant box repository. Skipping the addition to Vagrant.
NOTE: If you are having issues, try starting over by doing 'vagrant destroy' and then 'vagrant up'.
---------------------------------------------------------------------
SUCCESS: Run 'vagrant up' to provision and start metasploitable3.
NOTE: The VM will need Internet access to provision properly.

$ vagrant up
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
==> ub1404: Box file was not detected as metadata. Adding it directly...
==> ub1404: Adding box 'metasploitable3-ub1404' (v0) for provider: virtualbox
    ub1404: Downloading: metasploitable3-ub1404
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/qing/disk/udata/storage/sword/metasploitable3/metasploitable3-ub1404

**Comment by duncan426** [comment] 2018-04-05 12:31
Might try 
$vargrant up win2k8

**Comment by qingsword** [comment] 2018-04-05 12:56
Yes，you are right！Thanks duncan426！
It was installed successfully according to your method.

**Comment by qingsword** [comment] 2018-04-05 13:00
Hi duncan426，There are some problems.

    win2k8: Ok.
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/installs/install_share_autorun.bat as c:\tmp\vagrant-shell.bat
    win2k8:         1 file(s) copied.
    win2k8: The operation completed successfully.
==> win2k8: Running provisioner: shell...
    win2k8: Running: inline PowerShell script
==> win2k8: Running provisioner: shell...
    win2k8: Running: scripts/installs/setup_linux_share.bat as c:\tmp\vagrant-shell.bat
    win2k8: CMDKEY: Credential added successfully.
    win2k8: System error 67 has occurred.
    win2k8: The network name cannot be found.
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cmd /q /c "c:\tmp\vagrant-shell.bat"

Stdout from the command:


CMDKEY: Credential added successfully.


Stderr from the command:

System error 67 has occurred.

The network name cannot be found.

**Comment by Chan9390** [comment] 2018-04-19 18:03
Hey @qingsword , did you build the linux box using `./build.sh ubuntu1404` ?

**Comment by qingsword** [comment] 2018-04-20 05:39
Hey @Chan9390 ，Yes, I did.

**Comment by MauricioGamarra** [comment] 2018-06-21 13:57
great!!!!

**Comment by jmartin-r7** [comment] 2018-12-11 05:39
Please retry with latest `master`.  Closing as unable to reproduce and weekly builds now provided in vagrant cloud.

**Closed by jmartin-r7** 2018-12-11 05:39 UTC
