### ISSUE TITLE
Cannot complete build due to error about chocolatey.

### ISSUE THREAD

**Issue by JohnTill123** [rapid7/metasploitable3#576] opened 2022-09-23 15:18 UTC
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Packer Version: 1.6.6
* Vagrant Version: Vagrant 2.2.19
* VirtualBox Version: Version 6.1.38 r153438 (Qt5.15.3)

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.

Command:  packer build --only=qemu ./packer/templates/windows_2008_r2.json

OK until here:

==> qemu: Provisioning with shell script: /home/b84333/git/metasploitable3/packer/templates/../../scripts/installs/install_boxstarter.bat
==> qemu: 'chocolatey' is not recognized as an internal or external command,
==> qemu: operable program or batch file.
    qemu:
==> qemu: 'choco' is not recognized as an internal or external command,
    qemu: C:\Users\vagrant>chocolatey feature enable -n=allowGlobalConfirmation
    qemu:
==> qemu: operable program or batch file.
==> qemu: 'chocolatey' is not recognized as an internal or external command,
    qemu: C:\Users\vagrant>choco install BoxStarter
==> qemu: operable program or batch file.
    qemu:
    qemu: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> qemu: Deleting output directory...
Build 'qemu' errored after 12 minutes 37 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Wait completed after 12 minutes 37 seconds

==> Some builds didn't complete successfully and had errors:
--> qemu: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by highball8** [comment] 2022-10-01 18:03
I'm having what appears to be an identical issue, only I am trying to use both VirtualBox and VMware Fusion Pro.

# Host System

* OS: macOS 12.6 (Monterrey)
* Packer Version: 1.8.3
* Vagrant Version: 2.3.1
* VirtualBox Version: 6.1.38 r153438 (Qt5.6.3)
* VMware Fusion Pro Version: 12.2.4 (20071091)

# Command Output

The error is occurring with both variants of the command (VMware Fusion Pro and VirtualBox):
* `packer build --only=vmware-iso ./packer/templates/windows_2008_r2.json`
* `packer build --only=virtualbox-iso ./packer/templates/windows_2008_r2.json`

The error happens at the same place, after the second VM reboot.

## VirtualBox

```
==> virtualbox-iso: Provisioning with windows-shell...
==> virtualbox-iso: Provisioning with shell script: <local machine file path>/metasploitable3/packer/templates/../../scripts/installs/install_boxstarter.bat
    virtualbox-iso:
==> virtualbox-iso: 'chocolatey' is not recognized as an internal or external command,
==> virtualbox-iso: operable program or batch file.
    virtualbox-iso: C:\Users\vagrant>chocolatey feature enable -n=allowGlobalConfirmation
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>choco install BoxStarter
==> virtualbox-iso: 'choco' is not recognized as an internal or external command,
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
==> virtualbox-iso: operable program or batch file.
==> virtualbox-iso: 'chocolatey' is not recognized as an internal or external command,
==> virtualbox-iso: operable program or batch file.
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Cleaning up floppy disk...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored after 13 minutes 12 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Wait completed after 13 minutes 12 seconds

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

## VMware Fusion Pro

```
==> vmware-iso: Provisioning with windows-shell...
==> vmware-iso: Provisioning with shell script: <local machine file path>/metasploitable3/packer/templates/../../scripts/installs/install_boxstarter.bat
==> vmware-iso: 'chocolatey' is not recognized as an internal or external command,
    vmware-iso:
    vmware-iso: C:\Users\vagrant>chocolatey feature enable -n=allowGlobalConfirmation
    vmware-iso:
    vmware-iso: C:\Users\vagrant>choco install BoxStarter
==> vmware-iso: operable program or batch file.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>chocolatey feature disable -n=allowGlobalConfirmation
==> vmware-iso: 'choco' is not recognized as an internal or external command,
==> vmware-iso: operable program or batch file.
==> vmware-iso: 'chocolatey' is not recognized as an internal or external command,
==> vmware-iso: operable program or batch file.
==> vmware-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored after 13 minutes 24 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Wait completed after 13 minutes 24 seconds

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```

**Comment by jmartin-r7** [comment] 2023-02-04 20:57
This is likely a duplicate from the same root cause as #575, please retest with the fix that landed recently and reopen if the issue persists.

**Closed by jmartin-r7** 2023-02-04 20:57 UTC
