### ISSUE TITLE
An error occurred while downloading the remote file.

### ISSUE THREAD

**Issue by daraniya** [rapid7/metasploitable3#43] opened 2016-11-15 19:25 UTC
I get to the same point with the auto build or manual build:
➜  git-metasploitable3 git:(master) ./build_win2008.sh
Compatible version of VirtualBox found.
Compatible version of packer was found.
Correct version of vagrant was found.
A compatible version of vagrant-reload plugin was not found.
Attempting to install...
Installing the 'vagrant-reload' plugin. This can take a few minutes...
Installed the plugin 'vagrant-reload (0.0.1)'!
Successfully installed the vagrant-reload plugin.
All requirements found. Proceeding...
Building the Vagrant box...
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso
    virtualbox-iso: Download progress: 1%
    virtualbox-iso: Download progress: 3%
<clipped for brevity...>
    virtualbox-iso: Download progress: 100%
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: ./answer_files/2008_r2/Autounattend.xml
    virtualbox-iso: Copying file: ./scripts/configs/microsoft-updates.bat
    virtualbox-iso: Copying file: ./scripts/configs/win-updates.ps1
    virtualbox-iso: Copying file: ./scripts/installs/openssh.ps1
    virtualbox-iso: Copying file: ./resources/certs/oracle-cert.cer
    virtualbox-iso: Copying file: ./resources/certs/gdig2.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsadomainvalidationsecureserverca.crt
    virtualbox-iso: Copying file: ./resources/certs/comodorsacertificationauthority.crt
    virtualbox-iso: Copying file: ./resources/certs/addtrust_external_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/baltimore_ca.cer
    virtualbox-iso: Copying file: ./resources/certs/digicert.cer
    virtualbox-iso: Copying file: ./resources/certs/equifax.cer
    virtualbox-iso: Copying file: ./resources/certs/globalsign.cer
    virtualbox-iso: Copying file: ./resources/certs/gte_cybertrust.cer
    virtualbox-iso: Copying file: ./resources/certs/microsoft_root_2011.cer
    virtualbox-iso: Copying file: ./resources/certs/thawte_primary_root.cer
    virtualbox-iso: Copying file: ./resources/certs/utn-userfirst.cer
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2916)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1479227155 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1479227155 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: 127.0.0.1:5991
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Connected to SSH!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.6)
==> virtualbox-iso: Uploading VirtualBox guest additions ISO...
==> virtualbox-iso: Provisioning with shell script: ./scripts/installs/vm-guest-tools.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if not exist "C:\Windows\Temp\7z920-x64.msi" (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://www.7-zip.org/a/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')"  0<NUL )
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /i C:\Windows\Temp\7z920-x64.msi
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "vmware-iso" goto :vmware
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "virtualbox-iso" goto :virtualbox
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "TrustedPublisher" A:\oracle-cert.cer
    virtualbox-iso: TrustedPublisher
    virtualbox-iso: Certificate "CN=Oracle Corporation, OU=VirtualBox, OU=Digital ID Class 3 - Microsoft Software Validation v2, O=Oracle Corporation, L=Redwood Shores, S=California, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
    virtualbox-iso: 1 file(s) moved.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"
    virtualbox-iso:
    virtualbox-iso: 7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    virtualbox-iso:
    virtualbox-iso: Processing archive: C:\Windows\Temp\VBoxGuestAdditions.iso
    virtualbox-iso:
    virtualbox-iso: Extracting  32Bit
    virtualbox-iso: Extracting  32Bit\Readme.txt
    virtualbox-iso: Extracting  64Bit
    virtualbox-iso: Extracting  64Bit\Readme.txt
    virtualbox-iso: Extracting  AUTORUN.INF
    virtualbox-iso: Extracting  OS2
    virtualbox-iso: Extracting  OS2\VBoxControl.exe
    virtualbox-iso: Extracting  OS2\VBoxGuest.sys
    virtualbox-iso: Extracting  OS2\VBoxReplaceDll.exe
    virtualbox-iso: Extracting  OS2\VBoxService.exe
    virtualbox-iso: Extracting  OS2\gengradd.dll
    virtualbox-iso: Extracting  OS2\libc06.dll
    virtualbox-iso: Extracting  OS2\libc061.dll
    virtualbox-iso: Extracting  OS2\libc062.dll
    virtualbox-iso: Extracting  OS2\libc063.dll
    virtualbox-iso: Extracting  OS2\libc064.dll
    virtualbox-iso: Extracting  OS2\libc065.dll
    virtualbox-iso: Extracting  OS2\libc066.dll
    virtualbox-iso: Extracting  OS2\readme.txt
    virtualbox-iso: Extracting  OS2\vboxmouse.sys
    virtualbox-iso: Extracting  VBoxLinuxAdditions.run
    virtualbox-iso: Extracting  VBoxSolarisAdditions.pkg
    virtualbox-iso: Extracting  VBoxWindowsAdditions-amd64.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions-x86.exe
    virtualbox-iso: Extracting  VBoxWindowsAdditions.exe
    virtualbox-iso: Extracting  autorun.sh
    virtualbox-iso: Extracting  cert
    virtualbox-iso: Extracting  cert\VBoxCertUtil.exe
    virtualbox-iso: Extracting  cert\oracle-vbox.cer
    virtualbox-iso: Extracting  runasroot.sh
    virtualbox-iso:
    virtualbox-iso: Everything is Ok
    virtualbox-iso:
    virtualbox-iso: Folders: 4
    virtualbox-iso: Files: 26
    virtualbox-iso: Size:       58848147
    virtualbox-iso: Compressed: 59258880
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>goto :done
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /x C:\Windows\Temp\7z920-x64.msi
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/vagrant-ssh.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if exist a:\vagrant.pub (copy a:\vagrant.pub C:\Users\vagrant\.ssh\authorized_keys )  else (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub', 'C:\Users\vagrant\.ssh\authorized_keys')"  0<NUL )
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/disable-auto-logon.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoAdminLogon /d 0 /f
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/enable-rdp.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>netsh advfirewall firewall add rule name="Open Port 3389" dir=in action=allow protocol=TCP localport=3389
    virtualbox-iso: Ok.
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
    virtualbox-iso: The operation completed successfully.
==> virtualbox-iso: Provisioning with shell script: ./scripts/configs/update_root_certs.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\addtrust_external_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=AddTrust External CA Root, OU=AddTrust External TTP Network, O=AddTrust AB, C=SE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\baltimore_ca.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\digicert.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\equifax.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "OU=Equifax Secure Certificate Authority, O=Equifax, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\globalsign.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\gte_cybertrust.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=GTE CyberTrust Global Root, OU="GTE CyberTrust Solutions, Inc.", O=GTE Corporation, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\microsoft_root_2011.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\thawte_primary_root.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\utn-userfirst.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Preparing to export machine...
    virtualbox-iso: Deleting forwarded port mapping for the communicator (SSH, WinRM, etc) (host port 2916)
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export packer-virtualbox-iso-1479227155 --output output-virtualbox-iso/packer-virtualbox-iso-1479227155.ovf
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
==> virtualbox-iso (vagrant): Creating Vagrant box for 'virtualbox' provider
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/packer-virtualbox-iso-1479227155-disk1.vmdk
    virtualbox-iso (vagrant): Copying from artifact: output-virtualbox-iso/packer-virtualbox-iso-1479227155.ovf
    virtualbox-iso (vagrant): Renaming the OVF to box.ovf...
    virtualbox-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2008_r2.template
    virtualbox-iso (vagrant): Compressing: Vagrantfile
    virtualbox-iso (vagrant): Compressing: box.ovf
    virtualbox-iso (vagrant): Compressing: metadata.json
    virtualbox-iso (vagrant): Compressing: packer-virtualbox-iso-1479227155-disk1.vmdk
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'metasploitable3' (v0) for provider:
    box: Unpacking necessary files from: file:///Users/Bryan/git-metasploitable3/windows_2008_r2_virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

-----

Same error occurs building manually...

**Comment by getschwifty91** [comment] 2016-11-15 20:48
Yeah, I am stuck at the same spot. Have tried both Auto/Manually with the same outcome. Running it on OSX.

**Comment by daraniya** [comment] 2016-11-15 21:26
I too am on OSX...  Sierra 10.12.1

**Comment by emilhf** [comment] 2016-11-15 22:44
Experiencing the same problem. OS X 10.11, Vagrant 1.8.7, Packer 0.11.0, VirtualBox 5.1.6 (downgraded to cope with provisioning issues mentioned in the README).

The problem is caused by the embedded cURL binary shipped with Vagrant. The problem is easily solved by removing it with `sudo rm -rf /opt/vagrant/embedded/bin/curl`. Disclaimer: This **might** break other stuff (I don't know) so tread cautiously.

**Comment by getschwifty91** [comment] 2016-11-15 22:57
Instead of removing it: 
"sudo mv /opt/vagrant/embedded/bin/curl /opt/vagrant/embedded/bin/curlOLD

This has appeared to fix my issue since the version of curl used int Vagrant is broken on OSX

**Comment by daraniya** [comment] 2016-11-15 23:01
That appeared to work...  Great workaround until the real fix can be added

**Comment by jbarnett-r7** [comment] 2016-11-16 16:50
Thanks for finding a workaround. I'm still on Vagrant 1.8.6 so I'm going to see if 1.8.7 breaks it. If so I'll update the requirements to use 1.8.6 or lower.

**Comment by jbarnett-r7** [comment] 2016-11-16 17:48
Yup, it's definitely an issue with Vagrant 1.8.7. I'm on OSX 10.11.6. I found this issue on Vagrant's Github repo https://github.com/mitchellh/vagrant/issues/8002. I'm going to adjust the requirements to use 1.8.6 until it's fixed.

**Comment by jbarnett-r7** [comment] 2016-11-16 19:55
I updated the build script. Going to keep this open until the bug is fixed on Vagrant's end so I remember to remove this restriction.

**Comment by jbarnett-r7** [comment] 2017-01-05 19:18
This was fixed in Vagrant. Using the latest version will resolve the issue.

**Closed by jbarnett-r7** 2017-01-05 19:18 UTC
Labels: delayed

**Comment by Chan9390** [comment] 2017-05-12 06:58
@jbarnett-r7  What is the version of Vagrant you are using ?
