### ISSUE TITLE
"C:\Program Files\jenkins\jenkins.exe" is not recognized > exit status: 36

### ISSUE THREAD

**Issue by BaraSec** [rapid7/metasploitable3#196] opened 2017-10-22 16:48 UTC
## Issue Description

Hey, I am facing a issue that I can't resolve myself while building metasploitable 3 manually, tried twice, but the same error occurs, it happens when it tries to access "jenkins.exe" I see, I am not sure though. I am using **VMware Workstation** not virtualbox (forgot to use the "--only=vmware-iso" argument, is this what causes the problem ?!)

Thanks in advance, and I am sorry if I should have just googled more. 
Thanks for your time.

## Host System
* OS: **Windows 10 Pro fully updated**
* Packer Version: **1.1.1**
* Vagrant Version: **2.0.0**
* VirtualBox Version: **Using Vmware Workstation , 14.0.0 build-6661328**

## Command Output
```
    vmware-iso: Successfully processed 3435 files; Failed processing 0 files
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    vmware-iso: [SC] ChangeServiceConfig SUCCESS
==> vmware-iso: Provisioning with shell script: scripts/installs/start_glassfish_service.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>powershell -command "Start-Sleep -s 15"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>net start "domain1"
    vmware-iso: The domain1 GlassFish Server service is starting.
    vmware-iso: The domain1 GlassFish Server service was started successfully.
    vmware-iso:
==> vmware-iso: Provisioning with shell script: scripts/installs/setup_jenkins.bat
    vmware-iso:
    vmware-iso: C:\Users\vagrant>mkdir "C:\Program Files\jenkins"
    vmware-iso:
    vmware-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.war "C:\Program Files\jenkins"
    vmware-iso:         1 file(s) copied.
    vmware-iso:
    vmware-iso: '"C:\Program Files\jenkins\jenkins.exe"' is not recognized as an internal or external command,
    vmware-iso: C:\Users\vagrant>copy C:\vagrant\resources\jenkins\jenkins.exe "C:\Program Files\jenkins"
    vmware-iso: The system cannot find the file specified.
    vmware-iso: operable program or batch file.
    vmware-iso:
    vmware-iso: C:\Users\vagrant>"C:\Program Files\jenkins\jenkins.exe" -Service Install
    vmware-iso:
    vmware-iso: C:\Users\vagrant>sc config jenkins start= auto
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 36
--> virtualbox-iso: Failed creating VirtualBox driver: exec: "VBoxManage": executable file not found in %PATH%

==> Builds finished but no artifacts were created.

```

**Comment by Chan9390** [comment] 2017-10-22 19:05
I could not say that not using `--only=vmware-iso` is the cause for problem, but mentioning it configures the VM as per the VMware environment. 
Is `jenkins.exe` file present in `resources/jenkins` directory ?

**Comment by BaraSec** [comment] 2017-10-22 19:18
As I understood how it works, if nothing is specified, it will do both --only=vmware-iso and 
--only=virtualbox each on its own, as its environment!

.exe isn't, but jenkins.war is, wondering why and how !

**Comment by Chan9390** [comment] 2017-10-22 20:14
Thats the error. I think some antivirus or antimalware program has quarantined it. So please re-clone the repository, make sure the `jenkins.exe` file exists and then build the VM with the `vmware-iso` argument.

**Comment by BaraSec** [comment] 2017-10-22 20:20
I will.

Thanks a lot :)

**Comment by Chan9390** [comment] 2017-10-22 20:21
Don't forget to close the issue if it resolves.

**Comment by BaraSec** [comment] 2017-10-23 03:35
Yay. After re-cloning the repository, and re-downloading the iso:

```
    vmware-iso: C:\Users\vagrant>sc config "domain1" obj= "NT Authority\LOCAL SERVICE"
    vmware-iso: [SC] OpenService FAILED 1060:
    vmware-iso:
    vmware-iso: The specified service does not exist as an installed service.
    vmware-iso:
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 36

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Script exited with non-zero exit status: 36

==> Builds finished but no artifacts were created.
```

**Comment by Chan9390** [comment] 2017-10-23 04:20
Did `glassfish` install successfully ?
Please give me the output before the error.

**Comment by BaraSec** [comment] 2017-10-23 05:39
Exited powershell, but I copied the output from the first error, there were no errors before the above output as I remember.

**Comment by Chan9390** [comment] 2017-10-23 07:22
I could not comment anything based on the error. Please try to run the command again, upload the output in GitHub gist and comment it.

**Comment by BaraSec** [comment] 2017-10-23 09:46
Tried again and it didn't encounter the same errors again. Though `vagrant up` is asking me to enable hyper-v, is it gonna install the metasploitable3 vm in hyperV ? I want it to be in VMware workstation ! :/

Here is the output (last lines are the most important): https://gist.github.com/BaraSec/ad074b0ebda8b864ab44f81b865d54b7

**Comment by Chan9390** [comment] 2017-10-23 13:04
From the output, I could see that files [`hahaha.jpg`](https://gist.github.com/BaraSec/ad074b0ebda8b864ab44f81b865d54b7#file-metas3output-txt-L2884) and [`seven_of_hearts.html`](https://gist.github.com/BaraSec/ad074b0ebda8b864ab44f81b865d54b7#file-metas3output-txt-L2892) didnt copy correctly.

For vagrant to work with VMware, you have to buy the plugin. Check more at: https://www.vagrantup.com/vmware/

**Comment by BaraSec** [comment] 2017-10-23 13:11
Hmmm and should that be fixed ?! copy them by hand somehow ?
Wondering why all this errors, copying errors etc, are happening to me! I do everything the right way !

**Comment by BaraSec** [comment] 2017-10-23 13:13
And if I enabled hyper-v for vagrant, will I still be able to open vmware workstation and use the other VMs ?

Thanks for your time.

**Comment by Chan9390** [comment] 2017-10-23 17:10
I haven't used VMware and Windows for a long time. So I couldn't comment anything.

**Closed** 2017-10-23 17:44 UTC
