### ISSUE TITLE
Unable to install metasploitable3 win2k8

### ISSUE THREAD

**Issue by NoobPeng97** [rapid7/metasploitable3#564] opened 2022-02-10 02:51 UTC
## Issue Description
I have followed the quick-start guide on https://github.com/rapid7/metasploitable3 , i run the command listed one by one on powershell(admin) but it was unable to install the metasploitable 3-win2k8. It gave me this error 416 error code.
## Host System
* OS:Windows 10 Pro ver 21H2
* Packer Version: v1.7.10
* Vagrant Version: 2.2.19
* VirtualBox Version: Version 6.1.32 r149290 (Qt5.6.2)

## Command Output
==> win2k8: Box 'rapid7/metasploitable3-win2k8' could not be found. Attempting to find and install...
    win2k8: Box Provider: virtualbox
    win2k8: Box Version: >= 0
==> win2k8: Loading metadata for box 'rapid7/metasploitable3-win2k8'
    win2k8: URL: https://vagrantcloud.com/rapid7/metasploitable3-win2k8
==> win2k8: Adding box 'rapid7/metasploitable3-win2k8' (v0.1.0-weekly) for provider: virtualbox
    win2k8: Downloading: https://vagrantcloud.com/rapid7/boxes/metasploitable3-win2k8/versions/0.1.0-weekly/providers/virtualbox.box
==> win2k8: Box download is resuming from prior download progress
    win2k8:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 416
PS C:\Windows\system32\metasploitable3-workspace>

**Comment by truvatech** [comment] 2022-02-14 18:35
Second this. Image file 404s. Can fix by finding the replacement link for the image

`sudo packer build --only=qemu ./packer/templates/windows_2008_r2.json
qemu: output will be in this color.

<pre>[$ sudo packer build --only=qemu ./packer/templates/windows_2008_r2.json
<font color="#26A269"><b>qemu: output will be in this color.</b></font>

<font color="#26A269"><b>==&gt; qemu: Retrieving ISO</b></font>
<font color="#26A269"><b>==&gt; qemu: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso</b></font>
<font color="#26A269"><b>==&gt; qemu: Trying http://download.microsoft.com/download/7/5/E/75EC4E54-5B02-42D6-8879-D8D3A25FBEF7/7601.17514.101119-1850_x64fre_server_eval_en-us-GRMSXEVAL_EN_DVD.iso?checksum=md5%3A4263be2cf3c59177c45085c0a7bc6ca5</b></font>
<font color="#26A269"><b>==&gt; qemu: Download failed bad response code: 404</b></font>
<font color="#C01C28"><b>==&gt; qemu: error downloading ISO: [bad response code: 404]</b></font>
<font color="#C01C28"><b>Build &apos;qemu&apos; errored after 788 milliseconds 842 microseconds: error downloading ISO: [bad response code: 404]</b></font>

==&gt; Wait completed after 788 milliseconds 979 microseconds

==&gt; Some builds didn&apos;t complete successfully and had errors:
--&gt; qemu: error downloading ISO: [bad response code: 404]

==&gt; Builds finished but no artifacts were created.
</pre>

**Comment by johnroyer** [comment] 2022-02-27 09:54
Same issue. Download failed with HTTP 404.

**Comment by Louis-me** [comment] 2022-03-01 01:15
hi,you can download https://vagrantcloud.com/rapid7/boxes/metasploitable3-win2k8/versions/0.1.0-weekly/providers/virtualbox.box , you can look this [link](https://jeza-chen.com/2018/09/21/MetaSploit3_Setup/) ,work for me

**Comment by pwagener** [comment] 2022-03-04 02:33
This looks like a duplicate of #526.  And it looks like PR #563 fixes the problem.  The work-around is effectively what @truvatech mentioned... tweak the template JSON files & you're good to go.

**Comment by jmartin-r7** [comment] 2022-03-22 16:34
The download issue here was from `vagrantcloud` and not related to the other 404 issues for building with packer.  The `416` reported suggest you had a previous download cached from `vagrantcloud` that needs to be removed to start fresh.

**Closed** 2022-05-18 14:03 UTC

**Comment by mdvorscak** [comment] 2025-06-13 20:42
> Hmm for some reason it downloaded and booted but am getting an error related to "Windows could not apply the unattended answer file's setting.

I also had this issue trying to build from scratch with qemu, adding:
```json
      "disk_interface": "ide",
```
 to the `"type": "qemu"` template in the `windows_2008_r2.json` file fixed the issue.
