### ISSUE TITLE
BoxStarter not installed. The package was not found with the source(s) listed.

### ISSUE THREAD

**Issue by axcheron** [rapid7/metasploitable3#41] opened 2016-11-10 02:36 UTC
Hi,

I get an error when the provisioning process starts...

> ==> default: C:\Windows\system32>choco install BoxStarter 
==> default: Chocolatey v0.10.3
==> default: Installing the following packages:
==> default: 
==> default: BoxStarter
==> default: By installing you accept licenses for the packages.
==> default: **BoxStarter not installed. The package was not found with the source(s) listed.**
==> default: 
==> default:  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
==> default:  Version: ""
==> default:  Source(s): "https://chocolatey.org/api/v2/"
==> default: 
==> default: Chocolatey installed 0/1 packages. 1 packages failed.
==> default:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
==> default: 
==> default: Failures
==> default:  - BoxStarter - BoxStarter not installed. The package was not found with the source(s) listed.
==> default:  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.

I checked the connectivity on the VM, but everything is fine. Any ideas ?

**System: OS X 10.11.6
VBox 5.1.8
Vagrant 1.8.6**

## Update 1

According to this issue: https://github.com/chocolatey/choco/issues/1029, NAT seems to be the problem. I managed to manually install BoxStarter by changing my network adapter from NAT to Bridged, but of course it breaks Vagrant's port forward.

**Comment by axcheron** [comment] 2016-11-10 02:57
Changing my network settings from **NAT** to **Bridged** seems to fix this issue. I found some answers here: https://github.com/chocolatey/choco/issues/1029

**Comment by jbarnett-r7** [comment] 2016-11-10 19:24
Thank you for reporting this bug. We were actually seeing the same issue internally but hadn't been able to track down a root cause yet. I checked the issue thread you suggested and they suggested it might be a VirtualBox problem. 

Sure enough I found this [bug ticket on VirtualBox ](https://www.virtualbox.org/ticket/16084) describing a similar issue. The thread there suggests trying a test build of VirtualBox, 5.1.9 r111846. I installed that one and the issue is no longer present.

**Comment by axcheron** [comment] 2016-11-10 22:16
Thanks for your feedback. I downgraded VirtualBox from 5.1.8 to **5.1.6** and it works fine now.

**Comment by jbarnett-r7** [comment] 2016-11-11 16:36
Glad to hear it. I updated the docs to reflect the new requirements. I'll keep this issue open as a reminder to remove those requirements once the new version of VirtualBox is released

**Comment by Chiggins** [comment] 2016-11-16 04:25
Maybe just because I'm running Arch Linux and it's pretty cutting edge, but I was able to get Metasploitable built and running. VBoxManage -v says 5.1.8r111374

**Comment by semml0r** [comment] 2016-11-17 09:55
Current `build.sh` script states the following:
`sh build_win2008.sh
A compatible version of VirtualBox was not found. Currently only 5.1.9 is supported. Please download and install it from https://www.virtualbox.org/wiki/Download_Old_Builds_5_1.`
So this might be updated too, as 5.1.9 is not released as a public download. According to @axcheron it should point to version 5.1.6.

**Comment by jbarnett-r7** [comment] 2016-11-17 16:07
@semml0r That was my bad. I have that build installed locally so I was using that version when testing the script and forgot to fix it before committing. I just changed it back to 5.1.6.

**Comment by wvu-r7** [comment] 2016-12-02 21:33
Since people have been asking, you can find 5.1.6 downloads here: http://download.virtualbox.org/virtualbox/5.1.6.

**Comment by sersarov** [comment] 2016-12-22 22:51
I'm on OSX 10.11, and have VirtualBox 5.1.6 installed. However, when I run the build_win2008.sh script I get: 

A compatible version of VirtualBox was not found. Please download and install it from https://www.virtualbox.org/

Any ideas on what I've missed?

**Comment by jbarnett-r7** [comment] 2017-01-05 19:18
The latest version of VirtualBox does not have this issue.

**Closed by jbarnett-r7** 2017-01-05 19:18 UTC
Labels: delayed

**Comment by axcheron** [comment] 2017-01-06 19:53
I also checked, VirtualBox 5.1.12 (r112440) works fine.
